# Generated by Django 4.1.7 on 2023-04-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=32)),
                ('cover', models.TextField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=32)),
                ('user_email', models.CharField(max_length=32)),
                ('comment', models.TextField(max_length=255)),
                ('ratings', models.IntegerField()),
                ('date_submitted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32)),
                ('linkedin', models.CharField(max_length=32, null=True)),
                ('twitter', models.CharField(max_length=32, null=True)),
                ('facebook', models.CharField(max_length=32, null=True)),
                ('instagram', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32)),
                ('fullname', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('account_creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=32)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=64)),
                ('bio', models.TextField(max_length=255)),
                ('profile_picture', models.TextField(max_length=64)),
            ],
        ),
    ]
